import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


import Link from "next/link";
import ClientNavTools from "./ClientNavTools";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700;900&display=swap" rel="stylesheet" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="w-full px-6 py-2 flex justify-between items-center bg-[#0f172a] text-white text-sm font-sans">
          <span className="font-bold tracking-wide">YOUR WAY TO SAFETY</span>
          <span className="animate-pulse">New: Ask us about our latest certified PPE solutions!</span>
        </div>
        <nav className="w-full px-6 py-4 flex flex-wrap justify-center items-center gap-8 bg-[#111827] text-white font-sans text-lg font-medium shadow-md sticky top-0 z-50">
          <div className="flex flex-wrap gap-8 items-center">
            <Link href="/" className="hover:text-[#38bdf8] transition">Home</Link>
            <Link href="/about" className="hover:text-[#38bdf8] transition">About</Link>
            <Link href="/services" className="hover:text-[#38bdf8] transition">Services</Link>
            <Link href="/gallery" className="hover:text-[#38bdf8] transition">Gallery</Link>
            <Link href="/team" className="hover:text-[#38bdf8] transition">Team</Link>
            <Link href="/blog" className="hover:text-[#38bdf8] transition">Blog</Link>
            <Link href="/contact" className="hover:text-[#38bdf8] transition">Contact</Link>
          </div>
          <ClientNavTools />
        </nav>
        {children}
        {/* WhatsApp Floating Button */}
        <a href="https://wa.me/971551960890" target="_blank" rel="noopener noreferrer" className="fixed bottom-6 right-6 z-50 bg-green-500 hover:bg-green-600 text-white rounded-full shadow-lg p-4 flex items-center justify-center text-3xl animate-bounce" aria-label="Chat on WhatsApp">
          <span>💬</span>
        </a>
      </body>
    </html>
  );
}
